import Headphone1 from "../assets/Images/Headphones/headphone1.png";
import Headphone2 from "../assets/Images/Headphones/headphone2.png";
import Headphone3 from "../assets/Images/Headphones/headphone3.png";
import Headphone4 from "../assets/Images/Headphones/headphone4.png";
import Headphone5 from "../assets/Images/Headphones/headphone5.png";
import Headphone7 from "../assets/Images/Headphones/headphone7.png";
import Headphone8 from "../assets/Images/Headphones/headphone8.png";
import Headphone9 from "../assets/Images/Headphones/headphone9.png";
import Headphone10 from "../assets/Images/Headphones/headphone10.png";
import Headphone11 from "../assets/Images/Headphones/headphone11.png";
import Headphone12 from "../assets/Images/Headphones/headphone12.png";
import Headphone13 from "../assets/Images/Headphones/headphone13.png";
import Headphone14 from "../assets/Images/Headphones/headphone14.png";
import Headphone15 from "../assets/Images/Headphones/headphone15.png";
import Headphone16 from "../assets/Images/Headphones/headphone16.png";
import Headphone17 from "../assets/Images/Headphones/headphone17.png";
import Headphone18 from "../assets/Images/Headphones/headphone18.png";
import Headphone19 from "../assets/Images/Headphones/headphone19.png";
import Headphone20 from "../assets/Images/Headphones/headphone20.png";
import Earbud1 from "../assets/Images/Earbuds/earbud1.png";
import Earbud2 from "../assets/Images/Earbuds/earbud2.png";
import Earbud3 from "../assets/Images/Earbuds/earbud3.png";
import Earbud4 from "../assets/Images/Earbuds/earbud4.png";
import Earbud5 from "../assets/Images/Earbuds/earbud5.png";
import Earbud6 from "../assets/Images/Earbuds/earbud6.png";
import Earbud7 from "../assets/Images/Earbuds/earbud7.png";
import Speaker1 from "../assets/Images/Speakers/speaker1.png";
import Speaker2 from "../assets/Images/Speakers/speaker2.png";
import Speaker3 from "../assets/Images/Speakers/speaker3.png";
import Speaker4 from "../assets/Images/Speakers/speaker4.png";
import Speaker5 from "../assets/Images/Speakers/speaker5.png";
import Speaker6 from "../assets/Images/Speakers/speaker6.png";
import Speaker7 from "../assets/Images/Speakers/speaker7.png";
import Speaker8 from "../assets/Images/Speakers/speaker8.png";
import Speaker9 from "../assets/Images/Speakers/speaker9.png";
import Speaker10 from "../assets/Images/Speakers/speaker10.png";
import Speaker11 from "../assets/Images/Speakers/speaker11.png";
import Speaker12 from "../assets/Images/Speakers/speaker12.png";
import Speaker13 from "../assets/Images/Speakers/speaker13.png";
import Speaker14 from "../assets/Images/Speakers/speaker14.png";
import Speaker15 from "../assets/Images/Speakers/speaker15.png";
import Speaker16 from "../assets/Images/Speakers/speaker16.png";
import Speaker17 from "../assets/Images/Speakers/speaker17.png";

let idValue = 0;
export const productDb = [
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone1,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone2,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone3,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone4,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone5,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone1,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone7,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone8,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone9,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone10,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone11,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone12,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone13,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone14,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone15,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone16,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone17,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },
  {
    id: ++idValue,
    itemName: "MegaTron headphone",
    image: Headphone18,
    brand: "Beats 'b' Dre",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 123,
  },
  {
    id: ++idValue,
    itemName: "Stron bass headphone",
    image: Headphone19,
    brand: "Oraimo",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 113,
  },
  {
    id: ++idValue,
    itemName: "Hybrid headphone",
    image: Headphone20,
    brand: "New Age",
    type: "headphone",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 118,
  },

  // Earbuds data begins here

  {
    id: ++idValue,
    itemName: "Hybrid Earbud",
    image: Earbud1,
    brand: "New Age",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 128,
  },
  {
    id: ++idValue,
    itemName: "Tronix Earbud",
    image: Earbud2,
    brand: "Oraimo",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 112,
  },
  {
    id: ++idValue,
    itemName: "Hero II Earbud",
    image: Earbud3,
    brand: "Beats",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 125,
  },
  {
    id: ++idValue,
    itemName: "Sleek Earbud",
    image: Earbud1,
    brand: "New Age",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 178,
  },
  {
    id: ++idValue,
    itemName: "Hybrid Earbud",
    image: Earbud3,
    brand: "Virgin",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 148,
  },
  {
    id: ++idValue,
    itemName: "Tone-fox Earbud",
    image: Earbud6,
    brand: "Spink",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 108,
  },
  {
    id: ++idValue,
    itemName: "Tri-nux Earbud",
    image: Earbud7,
    brand: "Nux",
    type: "earbud",
    description: [
      "Pure bass",
      "HD Sound",
      "Multiple button control",
      "Comfortable ear covers",
    ],
    qty: 1,
    price: 198,
  },

  //The speakers data begins here
  {
    id: ++idValue,
    itemName: "Tronix Speaker",
    image: Speaker1,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 312,
  },
  {
    id: ++idValue,
    itemName: "Cybertron Speaker",
    image: Speaker2,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 212,
  },
  {
    id: ++idValue,
    itemName: "Bubble Speaker",
    image: Speaker3,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 412,
  },
  {
    id: ++idValue,
    itemName: "Griffin Speaker",
    image: Speaker4,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 324,
  },
  {
    id: ++idValue,
    itemName: "Huffle Speaker",
    image: Speaker5,
    brand: "Huff",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 320,
  },
  {
    id: ++idValue,
    itemName: "Satire II Speaker",
    image: Speaker6,
    brand: "Beats",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 289,
  },
  {
    id: ++idValue,
    itemName: "Atomix Speaker",
    image: Speaker7,
    brand: "beats",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 419,
  },
  {
    id: ++idValue,
    itemName: "Tronix Speaker",
    image: Speaker8,
    brand: "New age",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 220,
  },
  {
    id: ++idValue,
    itemName: "Iconic-duo Speaker",
    image: Speaker9,
    brand: "Icon",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 200,
  },
  {
    id: ++idValue,
    itemName: "Tronix Speaker",
    image: Speaker10,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 413,
  },
  {
    id: ++idValue,
    itemName: "Jingle-X Speaker",
    image: Speaker11,
    brand: "Jingle",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 312,
  },
  {
    id: ++idValue,
    itemName: "ParV Speaker",
    image: Speaker12,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 445,
  },
  {
    id: ++idValue,
    itemName: "ToneX Speaker",
    image: Speaker13,
    brand: "Tone",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 287,
  },
  {
    id: ++idValue,
    itemName: "Venom Speaker",
    image: Speaker14,
    brand: "Oraimo",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 448,
  },
  {
    id: ++idValue,
    itemName: "Xeon Speaker",
    image: Speaker15,
    brand: "XS",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 229,
  },
  {
    id: ++idValue,
    itemName: "Shutter Speaker",
    image: Speaker16,
    brand: "Beats",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 209,
  },
  {
    id: ++idValue,
    itemName: "GuggleT Speaker",
    image: Speaker17,
    brand: "Gugg",
    type: "speaker",
    description: ["Pure bass", "HD Sound", "Multiple button control"],
    qty: 1,
    price: 318,
  },
];
